### ISSUE TITLE
deepAssign error: Cannot convert undefined or null to object (server)

### ISSUE THREAD

**Issue by mehrancodes** [Fuzzyma/yata#2]
When I set the `server=true` in the config, I will get the following error. After I inspected the deepAssign's codes, I found that my Yata config must be identical with the Yata's default config, which was not.
Temporarily I fixed this error by changing the Yata's default conifg. So I will add a PR for this fix as well.

```js
(node:15683) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object (server)
    at assignKey (/home/mehran/code/..../node_modules/deep-assign/index.js:23:10)
    at assign (/home/mehran/code/..../node_modules/deep-assign/index.js:43:4)
    at assignKey (/home/mehran/code/..../node_modules/deep-assign/index.js:30:13)
    at assign (/home/mehran/code/..../node_modules/deep-assign/index.js:43:4)
    at deepAssign (/home/mehran/code/..../node_modules/deep-assign/index.js:64:3)
    at new Yata (/home/mehran/code/..../node_modules/yata/yata.js:36:19)
    at Server.app.listen (/home/mehran/code/..../devepement.js:60:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

**Comment by Fuzzyma** [comment]
Go ahead :)
